sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t sungjaejung1031/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sungjaejung1031/docker-react npm run test -- --coverage
